from django.db import models

# Create your models here.
class Title(models.Model):
    id = models.IntegerField(primary_key=True, blank=True)
    tid = models.CharField(max_length=16, null=False)
    updatefor = models.CharField(max_length=16, null=True)
    name = models.CharField(max_length=150)
    rating_id = models.IntegerField(null=True, blank=True)
    rating_normal_url = models.URLField(blank=True, null=True)
    rating_small_url = models.URLField(blank=True, null=True)   
    copyright = models.TextField(default='', blank=True, null=True)
    descriptor = models.ManyToManyField('descriptor', blank=True)
    desc = models.TextField(default='', blank=True, null=True)
    disclaimer = models.TextField(default='', blank=True, null=True)
    thumbnail_url = models.TextField(max_length=10000, null=False)
    icon_url = models.URLField(max_length=600, null=False)
    banner_url = models.URLField(max_length=600, null=False)
    screenshot_upper_url = models.TextField(max_length=10000, default='', blank=True, null=True)
    screenshot_lower_url = models.TextField(max_length=10000, default='', blank=True, null=True)
    movies = models.ManyToManyField("movie", blank=True)
    publisher = models.ForeignKey(publisher, on_delete=models.CASCADE)
    date = models.DateField(null=False, blank=False)
    product_code = models.CharField(max_length=30)
    new = models.BooleanField(default=True)
    public = models.BooleanField(default=True)
    categories = models.ManyToManyField(category,blank=True, related_name="titles")
    genre = models.ManyToManyField('genre')
    language = models.ManyToManyField('language', blank=True)
    number_of_players = models.CharField(max_length=6000, blank=True, null=True)
    in_app_purchase = models.BooleanField(default=False)
    platform = models.ForeignKey(platform, null=False, on_delete=models.CASCADE)
    price = models.DecimalField(default=0.00, null=False, max_digits=7, decimal_places=2)
    version = models.IntegerField(default=1024)
    on_sale = models.BooleanField(default=False)
    sale_price = models.DecimalField(default=0.00, null=False, max_digits=7, decimal_places=2)
    is_not_downloadable = models.BooleanField(default=False)
    size = models.IntegerField(default=0)
    ticket_available = models.BooleanField(default=True)
    demo = models.ForeignKey("title", on_delete=models.DO_NOTHING, null=True, blank=True)
    url_names = models.TextField(default="", blank=True)  
    urls = models.TextField(default="", blank=True)
    region = models.CharField(max_length=10000000000, default='CA, MX, US', blank=True, null=True)    
    keyword = models.ManyToManyField('keyword', blank=True)
    feature = models.ManyToManyField('feature', blank=True)
    target_player_everyone = models.IntegerField(null=True, blank=True)
    target_player_gamers = models.IntegerField(null=True, blank=True)
    play_style_casual = models.IntegerField(null=True, blank=True)
    play_style_intense = models.IntegerField(null=True, blank=True)
    rating_score = models.DecimalField(max_digits=5, decimal_places=2, default=0.00, blank=False, null=False)
    number_of_votes = models.IntegerField(default=0, blank=False, null=False)
    number_of_star1 = models.IntegerField(default=0, blank=False, null=False)
    number_of_star2 = models.IntegerField(default=0, blank=False, null=False)
    number_of_star3 = models.IntegerField(default=0, blank=False, null=False)
    number_of_star4 = models.IntegerField(default=0, blank=False, null=False)
    number_of_star5 = models.IntegerField(default=0, blank=False, null=False)
    def __str__(self):
        return self.name+" by "+self.publisher.publisher_name+" published on "+str(self.date)  