# Generated by Django 5.2.13 on 2026-04-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdeckdb', '0011_item_number_of_star1_item_number_of_star2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=32)),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='title',
            name='file3DS',
        ),
        migrations.RemoveField(
            model_name='title',
            name='file3DSX',
        ),
        migrations.RemoveField(
            model_name='title',
            name='fileCIA',
        ),
        migrations.RemoveField(
            model_name='title',
            name='galery_image_url',
        ),
        migrations.CreateModel(
            name='title_updates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('main_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_updates', to='shopdeckdb.title')),
                ('update_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_for', to='shopdeckdb.title')),
            ],
        ),
    ]
